name: Build & test

on: push

jobs:
  test-server:
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:54322/campaign-finance-test
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2.1.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd server && npm install
      - name: Run dockerized db
        run: docker-compose -f docker-compose.yml up -d postgres-test
      - name: Wait for db to be ready
        run: ./scripts/wait-for-postgres.sh ${TEST_DATABASE_URL}
      - name: Run tests
        run: cd server && npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test-server
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
